### ISSUE TITLE
Warning messages when loading model checkpoint in S2M project

### ISSUE THREAD

**Issue by MrBrilliant2046** [WenjieZhao1/S2M#1]
Description:

I'm encountering warning messages when loading the model checkpoint in the S2M project. These warnings suggest that some model parameters are not found in the checkpoint, and some keys in the checkpoint are not used by the model.

Environment:

Operating System: Ubuntu 22.04
Python version: 3.9
PyTorch version: 2.0.1

Steps to Reproduce:
    1. Clone the repository
    2. Install dependencies according to the README.md:
            Noted that setup.cfg requires Python 3.7, but requirements.txt requires Python 3.9.
            Installed packages using [special package manager] due to incompatibilities reported by pip.
    3. Attempt to install the project:
            Noticed that the pyproject.toml file is missing.
            Ran pip install -e . but encountered installation issues.
    4. Run the training script: cd ./tools
                                              python3 plain_train_net.py   --config-file ../configs/OE/OE.yaml   --num-gpus 1 SOLVER.IMS_PER_BATCH 4 SOLVER.BASE_LR 0.0025
    5. Received the following warning messages when loading the model checkpoint:
             WARNING [09/16 20:50:30 fvcore.common.checkpoint]: Some model parameters or buffers are not found in the checkpoint:
             backbone.fpn_lateral2.{bias, weight}
             backbone.fpn_lateral3.{bias, weight}
             backbone.fpn_lateral4.{bias, weight}
             backbone.fpn_lateral5.{bias, weight}
             backbone.fpn_output2.{bias, weight}
             backbone.fpn_output3.{bias, weight}
             backbone.fpn_output4.{bias, weight}
             backbone.fpn_output5.{bias, weight}
             proposal_generator.rpn_head.anchor_deltas.{bias, weight}
             proposal_generator.rpn_head.conv.{bias, weight}
             proposal_generator.rpn_head.objectness_logits.{bias, weight}
             roi_heads.box_head.fc1.{bias, weight}
             roi_heads.box_head.fc2.{bias, weight}
             roi_heads.box_predictor.bbox_pred.{bias, weight}
             roi_heads.box_predictor.cls_score.{bias, weight}
             WARNING [09/16 20:50:30 fvcore.common.checkpoint]: The checkpoint state_dict contains keys that are not used by the model:
             fc1000.{bias, weight}
              stem.conv1.bias
   6. Additional Context:
             Dependency Issues:
                  Found that setup.cfg specifies Python 3.7, but requirements.txt requires Python 3.9.
                  Some packages were incompatible, so I used [special package manager] to install them.
             Missing pyproject.toml File:
                  The absence of a pyproject.toml file caused installation issues.
             Attempts to Resolve:
                  Updated dependencies and adjusted the model configuration.
                  Tried adding a minimal setup.py and pyproject.toml, but the issue persists.
             Questions:
                  Do I need to use a specific code version or checkpoint file to resolve this?
                  Is there a recommended Python and library version setup for this project?

**Comment by WenjieZhao1** [comment]
Would you kindly complete the training and review the outcomes?
